"""
Django settings for studies_assistant project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Raiz do repositório (pasta acima de `backend/`) — para .env e chroma_data
REPO_ROOT = BASE_DIR.parent

# Etapa 4.1 — variáveis de ambiente (ficheiro `.env` na raiz do projeto)
load_dotenv(REPO_ROOT / '.env')
load_dotenv(BASE_DIR / '.env', override=True)

# Ollama — embeddings (nomic-embed-text)
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://127.0.0.1:11434').rstrip('/')
OLLAMA_EMBED_MODEL = os.environ.get('OLLAMA_EMBED_MODEL', 'nomic-embed-text:latest')
OLLAMA_EMBED_TIMEOUT = float(os.environ.get('OLLAMA_EMBED_TIMEOUT', '120'))
OLLAMA_EMBED_BATCH_SIZE = int(os.environ.get('OLLAMA_EMBED_BATCH_SIZE', '32'))

# ChromaDB — persistência local (ignorada pelo Git)
_chroma_raw = os.environ.get('CHROMA_PERSIST_DIR', 'chroma_data').strip()
_chroma_path = Path(_chroma_raw).expanduser()
CHROMA_PERSIST_PATH = (
    _chroma_path.resolve()
    if _chroma_path.is_absolute()
    else (REPO_ROOT / _chroma_path).resolve()
)
CHROMA_COLLECTION_NAME = os.environ.get('CHROMA_COLLECTION_NAME', 'study_documents')

# Etapa 4.3 — chunking (caracteres)
RAG_CHUNK_SIZE = int(os.environ.get('RAG_CHUNK_SIZE', '1500'))
RAG_CHUNK_OVERLAP = int(os.environ.get('RAG_CHUNK_OVERLAP', '200'))

# Etapa 5.1 — RAG: modelo de chat no Ollama e limites
OLLAMA_CHAT_MODEL = os.environ.get('OLLAMA_CHAT_MODEL', 'gemma2:2b').strip() or 'gemma2:2b'
OLLAMA_CHAT_TIMEOUT = float(os.environ.get('OLLAMA_CHAT_TIMEOUT', '180'))
RAG_TOP_K = max(1, min(50, int(os.environ.get('RAG_TOP_K', '5'))))
RAG_MAX_CONTEXT_CHARS = max(500, int(os.environ.get('RAG_MAX_CONTEXT_CHARS', '12000')))
RAG_MAX_QUESTION_LENGTH = max(10, int(os.environ.get('RAG_MAX_QUESTION_LENGTH', '4000')))
RAG_MAX_FILTER_DOCUMENTS = max(1, min(100, int(os.environ.get('RAG_MAX_FILTER_DOCUMENTS', '20'))))

# Etapa 5.5 — mensagem de sistema do RAG (opcional via .env)
_rag_sys = os.environ.get('RAG_SYSTEM_PROMPT', '').strip()
RAG_SYSTEM_PROMPT = _rag_sys or (
    'Responde só com base no contexto fornecido. '
    'Se não souberes ou a informação não estiver nesse contexto, '
    'diz claramente que não há informação nos documentos.'
)

# Etapa 5.7 — limite de pedidos ao endpoint RAG (DRF ScopedRateThrottle)
_rag_throttle_rate = os.environ.get('RAG_THROTTLE_RATE', '30/min').strip() or '30/min'
# Etapa 6 — chat (listar conversas / enviar mensagens)
_chat_throttle_rate = os.environ.get('CHAT_THROTTLE_RATE', '60/min').strip() or '60/min'
# Autenticação — força bruta / spam de contas (por IP)
_auth_login_throttle_rate = (
    os.environ.get('AUTH_LOGIN_THROTTLE_RATE', '5/min').strip() or '5/min'
) 
_auth_register_throttle_rate = (
    os.environ.get('AUTH_REGISTER_THROTTLE_RATE', '3/min').strip() or '3/min'
)
_auth_refresh_throttle_rate = (
    os.environ.get('AUTH_REFRESH_THROTTLE_RATE', '60/min').strip() or '60/min'
)
# Máximo de conversas por utilizador (0 = sem limite)
CHAT_MAX_CONVERSATIONS_PER_USER = max(
    0,
    int(os.environ.get('CHAT_MAX_CONVERSATIONS_PER_USER', '500')),
)
# Texto extraído do PDF anexado no chat enviado ao LLM (caracteres)
RAG_MAX_CHAT_ATTACHMENT_CONTEXT_CHARS = max(
    500,
    int(os.environ.get('RAG_MAX_CHAT_ATTACHMENT_CONTEXT_CHARS', '8000')),
)


# ---------------------------------------------------------------------------
# CORRIGIDO Bug 2: SECRET_KEY via variável de ambiente, nunca hardcoded.
#
# Em desenvolvimento, defina no ficheiro .env:
#   DJANGO_SECRET_KEY=qualquer-string-longa-e-aleatória
#
# Em produção, defina na variável de ambiente do servidor.
# Para gerar uma chave segura: python -c "from django.core.management.utils
#   import get_random_secret_key; print(get_random_secret_key())"
# ---------------------------------------------------------------------------
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    if 'test' in sys.argv:
        # Em testes, aceita uma chave padrão para não obrigar configuração extra
        SECRET_KEY = 'test-insecure-key-only-for-automated-tests-do-not-use-in-production'
    else:
        raise ValueError(
            'A variável de ambiente DJANGO_SECRET_KEY não está definida. '
            'Defina-a no ficheiro .env ou nas variáveis de ambiente do servidor. '
            'Para gerar uma chave segura execute: '
            'python -c "from django.core.management.utils import get_random_secret_key; '
            'print(get_random_secret_key())"'
        )

# ---------------------------------------------------------------------------
# CORRIGIDO Bug 3: DEBUG via variável de ambiente. Por defeito False (seguro).
#
# Para desenvolvimento, defina no ficheiro .env:
#   DJANGO_DEBUG=true
#
# NUNCA defina DJANGO_DEBUG=true num servidor de produção.
# ---------------------------------------------------------------------------
DEBUG = os.environ.get('DJANGO_DEBUG', 'false').strip().lower() in ('1', 'true', 'yes')

# ---------------------------------------------------------------------------
# CORRIGIDO Bug 4: ALLOWED_HOSTS via variável de ambiente.
#
# Em desenvolvimento, defina no ficheiro .env:
#   DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
#
# Em produção, inclua o domínio real:
#   DJANGO_ALLOWED_HOSTS=meusite.com,www.meusite.com
#
# Se DEBUG=True e ALLOWED_HOSTS não estiver definido, usa localhost por
# conveniência de desenvolvimento (sem arriscar produção).
# ---------------------------------------------------------------------------
_raw_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()

if _raw_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]
elif DEBUG:
    # Conveniência apenas em modo de desenvolvimento local
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    # Em produção sem a variável definida, falha explicitamente em vez de
    # deixar a lista vazia (que bloquearia todas as requisições) ou '*' (inseguro)
    raise ValueError(
        'A variável de ambiente DJANGO_ALLOWED_HOSTS não está definida. '
        'Defina-a com os domínios permitidos, ex.: '
        'DJANGO_ALLOWED_HOSTS=meusite.com,www.meusite.com'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'core',
    'documents',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studies_assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studies_assistant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# SQLite (predefinição) ou PostgreSQL via `DATABASE_URL` ou `USE_POSTGRES` + `POSTGRES_*`.


def _postgres_from_url(url: str) -> dict:
    u = urlparse(url)
    dbname = (u.path or '/').lstrip('/') or ''
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': dbname,
        'USER': unquote(u.username or ''),
        'PASSWORD': unquote(u.password or ''),
        'HOST': u.hostname or 'localhost',
        'PORT': str(u.port or 5432),
    }


def _build_databases() -> dict:
    db_url = os.environ.get('DATABASE_URL', '').strip()
    if db_url:
        return {'default': _postgres_from_url(db_url)}

    use_pg = os.environ.get('USE_POSTGRES', '').lower() in ('1', 'true', 'yes')
    pg_db = os.environ.get('POSTGRES_DB', '').strip()
    if use_pg and pg_db:
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': pg_db,
                'USER': os.environ.get('POSTGRES_USER', 'postgres'),
                'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
                'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
                'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            }
        }

    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


DATABASES = _build_databases()
# Testes: SQLite em memória (evita criar BD de teste no PostgreSQL sem permissões)
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Ficheiros enviados (PDFs) — Etapa 3
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
# Uploads até ~25 MB (limite alinhado com documents.serializers.MAX_PDF_BYTES)
DATA_UPLOAD_MAX_MEMORY_SIZE = 26 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST framework + JWT (Etapa 2.1)
# Utilizadores: modelo User padrão do Django (sem AbstractUser custom por agora).
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'core.exception_handler.exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.JWTCookieAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'rag': _rag_throttle_rate,
        'chat': _chat_throttle_rate,
        'auth_login': _auth_login_throttle_rate,
        'auth_register': _auth_register_throttle_rate,
        'auth_refresh': _auth_refresh_throttle_rate,
    },
}

if 'test' in sys.argv:
    REST_FRAMEWORK = {
        **REST_FRAMEWORK,
        'DEFAULT_THROTTLE_RATES': {
            **REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'],
            'rag': '100000/min',
            'chat': '100000/min',
            'auth_login': '100000/min',
            'auth_register': '100000/min',
            'auth_refresh': '100000/min',
        },
    }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    # Logout: POST /api/auth/logout/ — invalida refresh (cookie ou body) e apaga cookies
}

# JWT em cookies HttpOnly (SPA); nomes evitam colisão com outras apps no mesmo domínio
JWT_ACCESS_COOKIE_NAME = 'studies_access'
JWT_REFRESH_COOKIE_NAME = 'studies_refresh'
JWT_AUTH_COOKIE_PATH = '/api'
# None = automático: Lax+Secure=False em DEBUG; None+Secure=True em produção (cross-site HTTPS)
JWT_COOKIE_SAMESITE = os.environ.get('JWT_COOKIE_SAMESITE', '').strip() or None
_jwt_secure_raw = os.environ.get('JWT_COOKIE_SECURE', '').strip().lower()
if _jwt_secure_raw in ('1', 'true', 'yes'):
    JWT_COOKIE_SECURE = True
elif _jwt_secure_raw in ('0', 'false', 'no'):
    JWT_COOKIE_SECURE = False
else:
    JWT_COOKIE_SECURE = None

# CORS — origens do browser permitidas (obrigatório com credenciais; não uses '*').
# Desenvolvimento: deixa `DJANGO_CORS_ALLOWED_ORIGINS` vazio e usam-se os defaults do Vite.
# Produção: define no .env ou no servidor, por exemplo:
#   DJANGO_CORS_ALLOWED_ORIGINS=https://app.exemplo.com,https://www.exemplo.com
_cors_env = os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS', '').strip()
if _cors_env:
    CORS_ALLOWED_ORIGINS = []
    for _part in _cors_env.split(','):
        _o = _part.strip().rstrip('/')
        if _o:
            CORS_ALLOWED_ORIGINS.append(_o)
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ]
# Cookies de sessão na API precisam de credenciais CORS explícitas
CORS_ALLOW_CREDENTIALS = True

# Celery — processamento assíncrono de PDFs (upload). Em testes: execução síncrona (eager).
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0').strip()
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '').strip() or CELERY_BROKER_URL
CELERY_TASK_ALWAYS_EAGER = 'test' in sys.argv or os.environ.get(
    'CELERY_TASK_ALWAYS_EAGER', ''
).strip().lower() in ('1', 'true', 'yes')
CELERY_TASK_EAGER_PROPAGATES = True