"""
Django settings for studies_assistant project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Raiz do repositório (pasta acima de `backend/`) — para .env e chroma_data
REPO_ROOT = BASE_DIR.parent

# Etapa 4.1 — variáveis de ambiente (ficheiro `.env` na raiz do projeto)
load_dotenv(REPO_ROOT / '.env')
load_dotenv(BASE_DIR / '.env', override=True)

# Ollama — embeddings (nomic-embed-text)
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://127.0.0.1:11434').rstrip('/')
OLLAMA_EMBED_MODEL = os.environ.get('OLLAMA_EMBED_MODEL', 'nomic-embed-text:latest')
OLLAMA_EMBED_TIMEOUT = float(os.environ.get('OLLAMA_EMBED_TIMEOUT', '120'))
OLLAMA_EMBED_BATCH_SIZE = int(os.environ.get('OLLAMA_EMBED_BATCH_SIZE', '32'))

# ChromaDB — persistência local (ignorada pelo Git)
_chroma_raw = os.environ.get('CHROMA_PERSIST_DIR', 'chroma_data').strip()
_chroma_path = Path(_chroma_raw).expanduser()
CHROMA_PERSIST_PATH = (
    _chroma_path.resolve()
    if _chroma_path.is_absolute()
    else (REPO_ROOT / _chroma_path).resolve()
)
CHROMA_COLLECTION_NAME = os.environ.get('CHROMA_COLLECTION_NAME', 'study_documents')

# Etapa 4.3 — chunking (caracteres)
RAG_CHUNK_SIZE = int(os.environ.get('RAG_CHUNK_SIZE', '1500'))
RAG_CHUNK_OVERLAP = int(os.environ.get('RAG_CHUNK_OVERLAP', '200'))

# Etapa 5.1 — RAG: modelo de chat no Ollama e limites
OLLAMA_CHAT_MODEL = os.environ.get('OLLAMA_CHAT_MODEL', 'gemma2:2b').strip() or 'gemma2:2b'
OLLAMA_CHAT_TIMEOUT = float(os.environ.get('OLLAMA_CHAT_TIMEOUT', '180'))
RAG_TOP_K = max(1, min(50, int(os.environ.get('RAG_TOP_K', '5'))))
RAG_MAX_CONTEXT_CHARS = max(500, int(os.environ.get('RAG_MAX_CONTEXT_CHARS', '12000')))
RAG_MAX_QUESTION_LENGTH = max(10, int(os.environ.get('RAG_MAX_QUESTION_LENGTH', '4000')))
RAG_MAX_FILTER_DOCUMENTS = max(1, min(100, int(os.environ.get('RAG_MAX_FILTER_DOCUMENTS', '20'))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qeu34(rkg9xx8-xbtn-f$_@yisw14u88k4nhc14f=vvmk0ptjv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'core',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studies_assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studies_assistant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# SQLite (predefinição) ou PostgreSQL via `DATABASE_URL` ou `USE_POSTGRES` + `POSTGRES_*`.


def _postgres_from_url(url: str) -> dict:
    u = urlparse(url)
    dbname = (u.path or '/').lstrip('/') or ''
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': dbname,
        'USER': unquote(u.username or ''),
        'PASSWORD': unquote(u.password or ''),
        'HOST': u.hostname or 'localhost',
        'PORT': str(u.port or 5432),
    }


def _build_databases() -> dict:
    db_url = os.environ.get('DATABASE_URL', '').strip()
    if db_url:
        return {'default': _postgres_from_url(db_url)}

    use_pg = os.environ.get('USE_POSTGRES', '').lower() in ('1', 'true', 'yes')
    pg_db = os.environ.get('POSTGRES_DB', '').strip()
    if use_pg and pg_db:
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': pg_db,
                'USER': os.environ.get('POSTGRES_USER', 'postgres'),
                'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
                'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
                'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            }
        }

    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


DATABASES = _build_databases()


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Ficheiros enviados (PDFs) — Etapa 3
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
# Uploads até ~25 MB (limite alinhado com documents.serializers.MAX_PDF_BYTES)
DATA_UPLOAD_MAX_MEMORY_SIZE = 26 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST framework + JWT (Etapa 2.1)
# Utilizadores: modelo User padrão do Django (sem AbstractUser custom por agora).
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    # Logout: POST /api/auth/logout/ com body {"refresh":"..."} — invalida o refresh no servidor
}

# CORS — frontend Vite (mini-etapa 1.5)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
