# Generated by Django 5.2.13 on 2026-04-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
