# Generated by Django 5.2.13 on 2026-04-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_chunk_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedded_chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
