# Generated by Django 5.2.13 on 2026-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_embeddings_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chroma_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='chroma_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
