# Generated by Django 5.2.13 on 2026-05-01 12:24

from django.db import migrations, models


def _backfill_extraction_status(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    for d in Document.objects.iterator():
        if d.extraction_error:
            st = 'failed'
        elif d.extracted_text or d.chunk_count or d.chroma_indexed_at:
            st = 'done'
        else:
            st = 'pending'
        Document.objects.filter(pk=d.pk).update(extraction_status=st)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_chroma_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extraction_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Em fila'),
                    ('processing', 'A processar'),
                    ('done', 'Concluído'),
                    ('failed', 'Falhou'),
                ],
                db_index=True,
                default='pending',
                max_length=16,
            ),
        ),
        migrations.RunPython(_backfill_extraction_status, migrations.RunPython.noop),
    ]
